[net]
tickrate = 30

[netres]
limit = 25.0

[infolinks]
discord = "https://discord.ss14.ru"
github = "https://github.com/space-syndicate/space-station-14"
wiki = "https://station14.ru"
patreon = "https://boosty.to/corvax"
appeal = "https://discord.ss14.ru"
bug_report = "https://github.com/space-syndicate/space-station-14/issues/new/choose"
website = "https://ss14.ru"

[viewport]
maximum_width = 26

[game]
lobbyduration = 0
map_pool = "NextMapPool"
secret_weight_prototype = "CorvaxSecretDefault"
round_restart_time = 60

[server]
rules_file = "CorvaxRuleset"

[discord]
rich_main_icon_id = "corvax"

[admin]
see_own_notes = true

[game]
role_timers = false
enablewin = false

[ghost]
role_time = 0.5
quick_lottery = true

[ic]
ssd_sleep_time = 0

[shuttle]
auto_call_time = 0
emergency = false
arrivals = false