- type: job
  id: CentralCommandOfficial
  name: офицер штаба Центком
  description: job-description-centcomoff
  playTimeTracker: JobCentralCommandOfficial
  startingGear: CentcomGear
  icon: "JobIconCentcomm"
  supervisors: job-supervisors-centcom # Corvax-JobSupervisors
  canBeAntag: false
  whitelisted: true
  accessGroups:
  - AllAccess
  access:
  - CentralCommand
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant, DeathRattleImplantCentcomm ]

- type: startingGear
  id: CentcomGear
  equipment:
    id: CentcomPDA
    ears: ClothingHeadsetCentCom
    belt: WeaponPistolN1984
    pocket1: BoxFolderBlack